version: '3.8'

services:
  app:
    build: .
    container_name: kursovaya-app
    ports:
      - "3000:3000"
    volumes:
      - ./database.sqlite:/app/database.sqlite
    environment:
      - PORT=3000
      - JWT_SECRET=your_jwt_secret_key
      - DB_PATH=/app/database.sqlite
    restart: unless-stopped 