FROM node:18-alpine

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем файлы package.json и package-lock.json
COPY package*.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем исходный код проекта
COPY . .

# Устанавливаем переменные окружения для тестов
ENV NODE_ENV=test
ENV PORT=3000
ENV JWT_SECRET=test_secret_key
ENV DB_PATH=:memory:
ENV VITE_API_URL=http://server:3000

# Команда для запуска тестов
CMD ["npm", "run", "test:integration"] 